[parity]
chain = "../spec.json"
base_path = "parity_data"

[network]
port = 30303

[rpc]
port = 8511
apis = ["web3", "eth", "parity", "parity_set", "net", "traces", "rpc"]

[account]
password = ["../node.pwd"]
unlock = ["YOUR_ADDRESS"]

[mining]
usd_per_tx = "0"
min_gas_price = 0
force_sealing = true
engine_signer = "YOUR_ADDRESS"
gas_floor_target = "8000000"
reseal_on_txs = "none"


[misc]
log_file = "./parity.log"